# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"\x1f\n\tFactBasis\x12\x12\n\nanime_name\x18\x01 \x01(\t\"\x1b\n\x0c\x41nimeRequest\x12\x0b\n\x03\x61ge\x18\x01 \x01(\r\"\"\n\x0b\x41nimeAdvice\x12\x13\n\x0b\x61\x64vice_data\x18\x01 \x01(\t\"\x19\n\x04\x46\x61\x63t\x12\x11\n\tfact_data\x18\x01 \x01(\t2]\n\x0bTestService\x12#\n\x0etell_me_a_fact\x12\n.FactBasis\x1a\x05.Fact\x12)\n\nget_advice\x12\r.AnimeRequest\x1a\x0c.AnimeAdviceb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FACTBASIS._serialized_start=17
  _FACTBASIS._serialized_end=48
  _ANIMEREQUEST._serialized_start=50
  _ANIMEREQUEST._serialized_end=77
  _ANIMEADVICE._serialized_start=79
  _ANIMEADVICE._serialized_end=113
  _FACT._serialized_start=115
  _FACT._serialized_end=140
  _TESTSERVICE._serialized_start=142
  _TESTSERVICE._serialized_end=235
# @@protoc_insertion_point(module_scope)
